spring:
  application:
    name: currency-conversion-service
  cloud:
    config:
      uri: http://localhost:8088
  datasource:
    url: jdbc:${db.type}://${db.host}:${db.port}/${db.name}?reconnect=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimezone=${db.timezone}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:cfvnfrjq1}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate.ddl-auto: update
db:
  type: postgresql
  host: ${DB_HOST:localhost}
  port: 5432
  name: ${DB_NAME:currency_converter}
  timezone: Europe/Moscow
host:
  exchange.service: localhost:8100
  statistics.service: localhost:8200