server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: currency-conversion-main-service
          uri: lb://currency-conversion-main-service
          predicates:
            - Path=/exchange/**, /stats/**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}
        - id: currency-converter-statistics-service
          uri: lb://currency-converter-statistics-service
          predicates:
            - Path=/statistics/**
          filters:
            - RewritePath=/statistics/(?<path>.*), /$\{path}
        - id: currency-exchanger-service
          uri: lb://currency-exchanger-service
          predicates:
            - Path=/currency-exchange/**
          filters:
            - RewritePath=/currency-exchange/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs